#!/bin/bash

if [ $CODESPACES ]
then
  # Install neovim
	sudo apt-get install -y neovim

  # Copy vim config
  mkdir -p $HOME/.config/nvim
	cp -r nvim/* $HOME/.config/nvim/.

	#nvim +PlugInstall +qall
  #nvim +'PlugInstall --sync' +qall

  # Git aliases
	git config --global alias.co checkout
	git config --global alias.br branch
	git config --global alias.p push
	git config --global alias.st status
	git config --global alias.amend-no-edit "commit --amend --no-edit"

	alias pull="git pull"
  alias rebase-main="git fetch origin main && git rebase origin/main"
  alias format-changed="./node_modules/.bin/prettier -w  $(git diff --name-only)"

	# Git autocomplete
	curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
	source ~/.git-completion.bash
fi
