#!/bin/sh

# Install neovim
if [ $CODESPACES ]
then
	#apt-get install -y libfuse2
	#curl -L -o $HOME/bin/nvim https://github.com/neovim/neovim/releases/download/v0.6.1/nvim.appimage
	#chmod a+x $HOME/bin/nvim

	sudo apt-get install -y neovim
fi
